cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED MARC_CLI OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "MARC_CLI and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
set(input "${TEST_DIR}/input.bin")
set(output "${TEST_DIR}/protected.bin")
file(WRITE "${input}" "position-distance selection test")
file(WRITE "${output}" "keep-existing-output")

function(reject_selection)
    execute_process(COMMAND "${MARC_CLI}" ${ARGN} "${input}" "${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result EQUAL 2)
        message(FATAL_ERROR "Unsupported selection did not fail as usage: ${ARGN}: ${result}: ${stderr}")
    endif()
    file(READ "${output}" actual)
    if(NOT actual STREQUAL "keep-existing-output" OR EXISTS "${output}.tmp")
        message(FATAL_ERROR "Unsupported selection changed output")
    endif()
endfunction()

foreach(direction IN ITEMS encode decode)
    foreach(suffix IN ITEMS 1m 4m 16m 64m)
        reject_selection(${direction} --codec lzss-position-distance-dynamic-range-${suffix})
    endforeach()
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range --finder hash-chain-exact)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range --profile 1m)
endforeach()
