cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED MARC_CLI OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "MARC_CLI and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
set(input "${TEST_DIR}/input.bin")
set(output "${TEST_DIR}/protected.bin")
file(WRITE "${input}" "position-distance selection test")
file(WRITE "${output}" "keep-existing-output")

function(reject_selection)
    execute_process(COMMAND "${MARC_CLI}" ${ARGN} "${input}" "${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result EQUAL 2)
        message(FATAL_ERROR "Unsupported selection did not fail as usage: ${ARGN}: ${result}: ${stderr}")
    endif()
    file(READ "${output}" actual)
    if(NOT actual STREQUAL "keep-existing-output" OR EXISTS "${output}.tmp")
        message(FATAL_ERROR "Unsupported selection changed output")
    endif()
endfunction()

foreach(direction IN ITEMS encode decode)
    foreach(suffix IN ITEMS 32mx 128m)
        reject_selection(${direction} --codec lzss-position-distance-dynamic-range-${suffix})
    endforeach()
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range --finder hash-chain-exact)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range --profile 1m)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range-1m --finder hash-chain-exact)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range-1m --profile 1m)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range-1M)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range-4m --finder hash-chain-exact)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range-4m --profile 4m)
    reject_selection(${direction} --codec lzss-position-distance-dynamic-range-4M)
endforeach()

execute_process(COMMAND "${MARC_CLI}" RESULT_VARIABLE usage_result
    OUTPUT_VARIABLE usage_out ERROR_VARIABLE usage_err)
string(REGEX MATCHALL "lzss-position-distance-dynamic-range-1m" names "${usage_out}${usage_err}")
list(LENGTH names count)
if(NOT usage_result EQUAL 2 OR NOT count EQUAL 1)
    message(FATAL_ERROR "CLI inventory must list the 1 MiB position-distance selector exactly once")
endif()
string(REGEX MATCHALL "lzss-position-distance-dynamic-range-4m" four_mib_names "${usage_out}${usage_err}")
list(LENGTH four_mib_names four_mib_count)
if(NOT four_mib_count EQUAL 1)
    message(FATAL_ERROR "CLI inventory must list the 4 MiB position-distance selector exactly once")
endif()
