cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED MARC_BENCHMARK OR NOT DEFINED INPUT)
    message(FATAL_ERROR "Benchmark and input required")
endif()
execute_process(COMMAND "${MARC_BENCHMARK}" "${INPUT}" 1 4096 indexed distance-policies 2
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "AB failed: ${result}: ${error}")
endif()
foreach(key IN ITEMS position_decode_ab_pairs position_decode_ab_output_bytes frame_count
        position_distance_verified_frames position_distance_archive_bytes)
    string(REGEX MATCH "(^|\n)${key}=([0-9]+)" field "${output}")
    if(field STREQUAL "")
        message(FATAL_ERROR "Missing ${key}")
    endif()
    set(${key} "${CMAKE_MATCH_2}")
endforeach()
if(NOT position_decode_ab_pairs EQUAL 2 OR NOT frame_count EQUAL 1
    OR NOT position_distance_verified_frames EQUAL 1
    OR position_decode_ab_output_bytes LESS 1 OR position_distance_archive_bytes LESS 192)
    message(FATAL_ERROR "Incorrect AB extent")
endif()
foreach(pair RANGE 0 1)
    foreach(path IN ITEMS generic specialized)
        string(REGEX MATCH "position_decode_ab_${pair}_${path}_seconds=([0-9]+[.][0-9]+)" field "${output}")
        if(field STREQUAL "")
            message(FATAL_ERROR "Missing AB timing")
        endif()
    endforeach()
    string(REGEX MATCH "position_decode_ab_${pair}_verified_frames=([0-9]+)" field "${output}")
    if(field STREQUAL "" OR NOT CMAKE_MATCH_1 EQUAL 1)
        message(FATAL_ERROR "Missing verified pair")
    endif()
    math(EXPR expected "1 - ${pair}")
    string(REGEX MATCH "position_decode_ab_${pair}_generic_first_frames=([0-9]+)" field "${output}")
    if(field STREQUAL "" OR NOT CMAKE_MATCH_1 EQUAL expected)
        message(FATAL_ERROR "Incorrect alternating order")
    endif()
endforeach()
foreach(invalid IN ITEMS 0 21 invalid)
    execute_process(COMMAND "${MARC_BENCHMARK}" "${INPUT}" 1 4096 indexed distance-policies "${invalid}"
        RESULT_VARIABLE result OUTPUT_VARIABLE ignored ERROR_VARIABLE error TIMEOUT 10)
    if(NOT result EQUAL 2)
        message(FATAL_ERROR "Invalid pair count was not rejected")
    endif()
endforeach()
