if(NOT DEFINED DIAGNOSTIC OR NOT DEFINED FIXTURE_GENERATOR OR NOT DEFINED WORK)
    message(FATAL_ERROR "Missing diagnostic, fixture generator or workspace")
endif()
# Retain each invocation independently, including failures.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef invocation)
set(WORK "${WORK}/run-${invocation}")
if(EXISTS "${WORK}")
    message(FATAL_ERROR "Diagnostic destination already exists")
endif()
file(MAKE_DIRECTORY "${WORK}")
file(WRITE "${WORK}/empty" "")
string(REPEAT "A" 259 run)
file(WRITE "${WORK}/run" "${run}")
string(REPEAT "abcabcabc0123456789" 227 data)
file(WRITE "${WORK}/small" "${data}")
foreach(member empty run small)
    execute_process(COMMAND "${FIXTURE_GENERATOR}" "${WORK}/${member}" position4m-reference verify "${WORK}/${member}.marc"
        RESULT_VARIABLE result OUTPUT_VARIABLE generated ERROR_VARIABLE error)
    file(WRITE "${WORK}/${member}-generation.log" "${generated}${error}")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture generation failed")
    endif()
    execute_process(COMMAND "${DIAGNOSTIC}" "${WORK}/${member}" "${WORK}/${member}.marc"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${WORK}/${member}.log" "${output}${error}")
    if(NOT result EQUAL 0 OR NOT output MATCHES "verified=1" OR output MATCHES "seconds=")
        message(FATAL_ERROR "Diagnostic failed: ${result} ${error} ${output}")
    endif()
    if(NOT member STREQUAL "empty" AND NOT output MATCHES "frame_0_insertions_5=[0-9]+")
        message(FATAL_ERROR "Missing counter output")
    endif()
endforeach()
file(WRITE "${WORK}/bad.marc" "bad")
file(COPY_FILE "${WORK}/small.marc" "${WORK}/trailing.marc")
file(APPEND "${WORK}/trailing.marc" "bad")
file(SIZE "${WORK}/small.marc" archive_size)
math(EXPR truncated_size "${archive_size}-1")
file(READ "${WORK}/small.marc" truncated LIMIT ${truncated_size})
file(WRITE "${WORK}/truncated.marc" "${truncated}")
foreach(member bad trailing truncated)
    execute_process(COMMAND "${DIAGNOSTIC}" "${WORK}/small" "${WORK}/${member}.marc"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${WORK}/${member}.log" "result=${result}\n${output}${error}")
    if(NOT result EQUAL 1 OR NOT output STREQUAL "")
        message(FATAL_ERROR "Failed archive published diagnostic output: ${member}")
    endif()
endforeach()
